import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, Theme } from '@radix-ui/themes';
import NavBar from './NavBar';
import { CartProvider } from './CartContext';
import CartIcon from './components/CartIcon';
import { ThemeProvider } from 'next-themes'

import ShowCartIcon from './ShowCartIcon';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        <ThemeProvider attribute='class'>
        <Theme accentColor='grass'>
        <NavBar />
       
        <main>
          <Container>
            {children}
           <ShowCartIcon />
            </Container></main>
        </Theme></ThemeProvider></CartProvider>
        </body>
    </html>
  );
}
